### ISSUE TITLE
chalk item appears everywhere in REI

### ISSUE THREAD

**Issue by SandWoodJones** [DaFuqs/Chalk#4]
When using REI no matter what the search query is the chalk item shows up. This only happens with the not-glowing version.
![photo_2021-12-03_03-47-18](https://user-images.githubusercontent.com/35671374/144558062-2e5ad077-df3a-4839-8825-b81f4f3fccd9.jpg)

**Comment by DaFuqs** [comment]
I could reproduce that with just Chalk and REI installed on 1.18.

The thing is Chalk is not touching REI at all. Looking at the issue tracker of REI there seem to be similar reports for other mods, since 10 days ago.
- https://github.com/shedaniel/RoughlyEnoughItems/issues/667
- https://github.com/shedaniel/RoughlyEnoughItems/issues/673

Therefore, it seems more like an issue with newer versions of REI in general. I will leave this issue open for the time being until it is resolved.

@shedaniel If I can help you out in any way whatsoever - or you think that is indeed an issue with Chalk that I need to resolve - just message me and I would be happy to help.
The items specs in question are:
"chalk:chalk" named "Chalk": will not get filtered out
"chalk:glow_chalk" named "Glow Chalk": is getting filtered out

**Comment by shedaniel** [comment]
Need the latest.log and open an issue

**Comment by DaFuqs** [comment]
REI issue.
